### ISSUE TITLE
Product.cs does not contain a "tag" property

### ISSUE THREAD

**Issue by weslbo** [MicrosoftLearning/dp-420-cosmos-db-dev#14]
# Module: 05
## Step: 15

Description of issue

Repro steps:

Product.cs does not contain a "tag" property. However the sql command and the final c# code are referencing the tag property.

```csharp
public class Product
{
	public string id { get; set; }
	public string categoryId { get; set; }
	public string categoryName { get; set; }
	public string sku { get; set; }
	public string name { get; set; }
	public string description { get; set; }
	public double price { get; set; }
}
```

```sql
SELECT p.name, t.name AS tag FROM products p JOIN t IN p.tags
```

**Comment by weslbo** [comment]
Step 15 is asking to write following statement: (which fails)

```csharp
Console.WriteLine($"[{product.name,40}]\t{product.tag}");
```

**Comment by MScalopez** [comment]
Wes, thanks for bringing this up to us, I will review the issue and fixed it as soon as possible.

**Comment by MScalopez** [comment]
Issue has been fixed.  Again, thank you for bringing this to our attention.
