### ISSUE TITLE
M:4 - L:06 - T:Connect to the Azure Cosmos DB SQL API account from the SDK S:8

### ISSUE THREAD

**Issue by chris-utter** [MicrosoftLearning/dp-420-cosmos-db-dev#15]
# Module: 04
#### Step: 08

Description of issue
Step 8 references the emulator, but the lab is connected to a real CosmosDB account.

"Asynchronously invoke the CreateDatabaseIfNotExistsAsync method of the client variable passing in the name of the new database (cosmicworks) you would like to create within the emulator and storing the result in a variable of type Database:"

**Comment by MScalopez** [comment]
Thanks for bringing this up to our team Chris, I have fixed the incorrect reference to the emulator.
