### ISSUE TITLE
Unable to Execute Query

### ISSUE THREAD

**Issue by tyrone0501** [MicrosoftLearning/dp-420-cosmos-db-dev#18]
# Module: 05
#### Step: 14

Description of issue
Every time I try to run the query the following error appears:

handled exception. System.MissingMethodException: Method not found: 'System.String Microsoft.Azure.Documents.IAuthorizationTokenProvider.GetUserAuthorizationToken(System.String, System.String, System.String, Microsoft.Azure.Documents.Collections.INameValueCollection, Microsoft.Azure.Documents.AuthorizationTokenType, System.String ByRef)'.

Repro steps:

Included the following code with the correct endpoints and keys:

using System;
using Azure.Cosmos;

string endpoint = "<cosmos-endpoint>";

string key = "<cosmos-key>";

CosmosClient client = new CosmosClient(endpoint, key);

CosmosDatabase database = await client.CreateDatabaseIfNotExistsAsync("cosmicworks");

CosmosContainer container = await database.CreateContainerIfNotExistsAsync("products", "/categoryId");

string sql = "SELECT * FROM products p";
QueryDefinition query = new (sql);

await foreach (Product product in container.GetItemQueryIterator<Product>(query))
{
    Console.WriteLine($"[{product.id}]\t{product.name,35}\t{product.price,15:C}");
}

and received an error when I tried to run the application with donet run

**Comment by MScalopez** [comment]
Reviewing issue

**Comment by safersephy** [comment]
It's probably best to update the used package to Microsoft.Azure.Cosmos and adapt the new pattern to iterate.

Replace:

`await foreach (Product product in container.GetItemQueryIterator<Product>(query))
{
    Console.WriteLine($"[{product.id}]\t{product.name,35}\t{product.price,15:C}");
}`

With:

`using FeedIterator<Product> feed = container.GetItemQueryIterator<Product>(
    queryDefinition: query
);

while (feed.HasMoreResults)
{
    FeedResponse<Product> response = await feed.ReadNextAsync();
    foreach (Product item in response)
    {
        Console.WriteLine($"[{item.id}]\t{item.name,35}\t{item.price,15:C}");
    }
}`

I'd contribute myself but sadly i'm not a MCT :(

**Comment by ejneuman** [comment]
When you first open **script.cs** in Lab 09, you need to run the following terminal commands to make sure the code compiles correctly with the newer version of the framework.

1. dotnet remove package Microsoft.Azure.Cosmos
2. dotnet add package Azure.Cosmos --version 4.0.0-preview3
3. dotnet build

You can then proceed as directed.

**Comment by MScalopez** [comment]
issue has been fixed
