### ISSUE TITLE
Lab 01 Recommended Click Step Change

### ISSUE THREAD

**Issue by ejneuman** [MicrosoftLearning/dp-420-cosmos-db-dev#19]
In Lab 01, I believe the following click step should be changed:

4. In the **Select API option** pane, select the Create option within the **Core (SQL) - Recommended** section.

Think this should be:

4. In the **Select API option** pane, select the Create option within the **Azure Cosmos DB for NoSQL** section.

**Comment by ejneuman** [comment]
I wanted to note that I had initially reported this as an issue with Lab 01, but this same inaccuracy actually persists through most of the labs, when you instruct users to create a Cosmos DB in the Azure portal.

**Comment by MScalopez** [comment]
This has been fixed
