### ISSUE TITLE
Fix for Lab 09

### ISSUE THREAD

**Issue by ejneuman** [MicrosoftLearning/dp-420-cosmos-db-dev#22]
When you first open **script.cs** in Lab 09, you need to run the following terminal commands to make sure the code compiles correctly with the newer version of the framework.

1. dotnet remove package Microsoft.Azure.Cosmos
2. dotnet add package Azure.Cosmos --version 4.0.0-preview3
3. dotnet build

You can then proceed as directed.

**Comment by MScalopez** [comment]
Reviewing this issue, do note we can no use a preview version (--version 4.0.0-preview3) for these labs.

**Comment by MScalopez** [comment]
Lab errors fixed.
