### ISSUE TITLE
Environment Setup Issue

### ISSUE THREAD

**Issue by ejneuman** [MicrosoftLearning/dp-420-cosmos-db-dev#24]
In 00-setup-environment, you should also specify to install the Azure CLI from https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli.

This is necessary, for example, in Lab 16 when you need to run the az commands.

**Comment by MScalopez** [comment]
Reviewing issue

**Comment by MScalopez** [comment]
Issue was fixed in lab 16, thank you.
