### ISSUE TITLE
Lab 17 Issue

### ISSUE THREAD

**Issue by ejneuman** [MicrosoftLearning/dp-420-cosmos-db-dev#25]
If you try and run Lab 17 - Denormalize right after Lab 16, you will run into the following error when executing the "dotnet run" command:

Unhandled exception. Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: Conflict (409); Substatus: 0; ActivityId: 38f1b7a1-3487-4549-b1a6-1356c2b051d4; Reason: (
Errors : [
  "Resource with specified id or name already exists."
]

To fix this, you need to first manually delete the CosmosDB database created in Lab 16, so you can recreate it here.

Suggested fix would be to create a difference resource in Lab 17 than "cosmicworks-q46mjbiavkfgg".  Each lab should have uniquely named resources.

**Comment by MScalopez** [comment]
Reviewing issues

**Comment by MScalopez** [comment]
These labs are meant to be run individually,
