### ISSUE TITLE
"Create a composite index in the indexing policy" not possible with the default cosmos db indexing policy 

### ISSUE THREAD

**Issue by ChangeTheCode** [MicrosoftLearning/dp-420-cosmos-db-dev#3]
# Module: dp-420-cosmos-db-dev
### Task: Create a composite index in the indexing policy

Description of issue
If I follow the description in the tutorial for "Create a composite index in the indexing policy" I got an error message from the Cosmos DB engine. 

Section:
```
 In the Data Explorer, expand the cosmicworks database node, select the products container node, and then select New SQL Query.

Delete the contents of the editor area.

Create a new SQL query that will order the results by the categoryName in descending order first, and then by the price in ascending order:

SELECT 
    p.name,
    p.categoryName,
    p.price
FROM
    products p
ORDER BY
    p.categoryName DESC,
    p.price ASC
Select Execute Query.

Observe the results and stats of the query. The request unit charge should be pretty high since we do not have a composite index for the multiple order-by expressions.
```

Repro steps:

1. Follow all described steps to create an azure cosmos db account => database and container 
2. Navigate to "In the Data Explorer, expand the cosmicworks database node, select the products container node, and then select New SQL Query."
3. Execute the following query 
 ```sql 
SELECT 
    p.name,
    p.categoryName,
    p.price
FROM
    products p
ORDER BY
    p.categoryName DESC,
    p.price ASC
``` 

**Error:** "Failed to query item for container products:
 Message: {"Errors":["The order by query does not have a corresponding composite index that it can be served from."]}"

**Comment by MScalopez** [comment]
Thank you for bringing this up to the team, we have corrected the step by indicating that this query will error out.
