### ISSUE TITLE
Lab 27 Issue - Continuous Backup Option Has Moved

### ISSUE THREAD

**Issue by ejneuman** [MicrosoftLearning/dp-420-cosmos-db-dev#32]
In the Optional section of Lab 27 to enable continuous backup, this feature has moved.  It is no longer on the Features screen under Settings.  Instead:

Under the **Settings** section, select **Backup & Restore**.
Next to Backup policy mode, select **(change)**.
Select **Continuous (7 Days)**.
Click **Save**.

**Comment by MScalopez** [comment]
fixing in issue [35](https://github.com/MicrosoftLearning/dp-420-cosmos-db-dev/issues/35)
