### ISSUE TITLE
Lab 32 Observations

### ISSUE THREAD

**Issue by ejneuman** [MicrosoftLearning/dp-420-cosmos-db-dev#34]
Through some weird quirk of the New Stored Procedure UI, I was unable to save the document if I first typed in the title, and then added the code to the stored procedure.  What DID work was to add the code first, and THEN type in the title.

In the final block of code you paste into the stored procedure, you might think about including the comma that needs to be added so it doesn't get missed, like this:

,
(error, newDoc) => {
  if (error) throw new Error(error.message);
  context.getResponse().setBody(newDoc);
}

**Comment by MScalopez** [comment]
added missing comma
