### ISSUE TITLE
Lab 27 - Issue when trying to restore

### ISSUE THREAD

**Issue by Mihai-Ac** [MicrosoftLearning/dp-420-cosmos-db-dev#35]
#### Step: 1

Description of issue

When opening the **Point In Time Restore** page, there is an error which stops the student from continuing with the exercise.
![image](https://user-images.githubusercontent.com/110993710/218715438-c8be2b14-7368-4255-ad17-d9f36a8f00c4.png)

Seems to be an account authorization issue.

**Comment by MScalopez** [comment]
Working with our backend team to get this permissions issue resolved.

**Comment by MScalopez** [comment]
Working with the Product Team to find a solution to this permission's issue.

**Comment by MScalopez** [comment]
Unluckily there is a permission on the student account creation that cant be fixed because it is set on the subscription side.  We have decided to change this lab to be BYoS (Bring your own Subscription).
