### ISSUE TITLE
Lab 30 : Error in Create Azure Cosmos DB account using Azure CLI

### ISSUE THREAD

**Issue by Mihai-Ac** [MicrosoftLearning/dp-420-cosmos-db-dev#36]
#### Step: 8. Create a new Azure Cosmos DB account using the predefined variables and the following command:
az cosmosdb create --name $accountName --resource-group $resourceGroup

Description of issue
When running the code an error pointing at credential access scope:
![image](https://user-images.githubusercontent.com/110993710/219022342-a91e375a-3b91-4fe5-b609-99f4e988b385.png)

**Comment by MScalopez** [comment]
This might have been a temporary issue, I tested this labs both on the backend VMs and the production ones an was successfully able to create the Azure Cosmos DB account as you can see on the attached screenshot below.

![image](https://user-images.githubusercontent.com/87540998/224129992-1eba85f0-e449-450e-b272-ce1468468039.png)
