### ISSUE TITLE
Lab 28 Issue

### ISSUE THREAD

**Issue by Mihai-Ac** [MicrosoftLearning/dp-420-cosmos-db-dev#37]
#### Step: 4. Add the [Microsoft.Azure.Services.AppAuthentication][nuget.org/packages/Microsoft.Azure.Services.AppAuthentication] package from NuGet using the following command:

dotnet add package Microsoft.Azure.Services.AppAuthentication

Description of issue
Error : **There are no versions available for the package ´Microsoft.Azure.Services.AppAuthentication´.**
![image](https://user-images.githubusercontent.com/110993710/219023466-f8e9ce41-d763-45db-bd81-7849fb79ac67.png)

After that, in the Deploy your application to Azure App Services, on step 17,selecting the folder to deploy, this happens:
![image](https://user-images.githubusercontent.com/110993710/219023965-250c913d-265c-4788-84dc-bb4c888665ab.png)

Selecting **Deploy anyway** will result in an error :
![image](https://user-images.githubusercontent.com/110993710/219024093-3bd43638-e91d-4399-ac9e-19232b8ae2e9.png)

**Comment by MScalopez** [comment]
After some research, it appears like we have depricated the Microsoft.Azure.Services.AppAuthentication library and replaced it with the Azure.Identity one and it appears like NuGet is no longer providing the deprecated one.  I am in the process of re-writing this script to use the Azure.Identity library.

**Comment by WigF1** [comment]
The fix is simple in the short-term. Simply add the version on to the instruction.

dotnet add package Microsoft.Azure.Services.AppAuthentication --version 1.6.2

**Comment by MScalopez** [comment]
Thank you @WigF1, the fixes are scheduled to go in Monday.

**Comment by MScalopez** [comment]
Fix was done a while back
