### ISSUE TITLE
Lab 31 : Deploy the Bicep template using the az deployment group create command:

### ISSUE THREAD

**Issue by Mihai-Ac** [MicrosoftLearning/dp-420-cosmos-db-dev#38]
#### Step: 07 :Deploy the Bicep template using the az deployment group create command:

az deployment group create --name "bicep-deploy-account" --resource-group $resourceGroup --template-file .\deploy.bicep

Description of issue: 
When running the code, there is an issue with the account authorization:
![image](https://user-images.githubusercontent.com/110993710/219030337-b9d6e9ae-757b-4cbd-8dfb-3e62c987f41d.png)

**Comment by MScalopez** [comment]
This most likely was a temporary issue, I have run the lab on both the backend vms and the production vms and had no issues running every step of this lab, including step 7.  Please look at the result below.

![image](https://user-images.githubusercontent.com/87540998/223861810-fb5eac38-7a25-4bd2-af41-0e9d8f75c70a.png)
