### ISSUE TITLE
Lab 25: no json sample files provided

### ISSUE THREAD

**Issue by KoenVerbeeck** [MicrosoftLearning/dp-420-cosmos-db-dev#40]
# Module: 11
#### Step: Build and run the project using the dotnet run command

When you run the code on your own machine, targeting your own cosmos db instance, you get an error because it can't find the json files with the sample data.

![image](https://user-images.githubusercontent.com/7213731/220963370-4f58946c-9956-4269-8aa9-0d5cf09e7428.png)

Repro steps:

1. Follow the steps described in https://github.com/MicrosoftLearning/dp-420-cosmos-db-dev/blob/main/instructions/25-monitor.md
2. Copy the program.cs code (https://github.com/MicrosoftLearning/dp-420-cosmos-db-dev/blob/main/25-monitor/Program.cs) into your own solution and run it.
3. It crashes, because there are no json files.

**Comment by MScalopez** [comment]
@KoenVerbeeck, the good news, you should be able to find the dataset at https://github.com/MicrosoftLearning/dp-420-cosmos-db-dev/tree/main/data, download it and it should allow you to run the lab on your local machine.
