### ISSUE TITLE
Module 3 - Connect to Azure Cosmos DB for NoSQL with the SDK' - Stop the Azure Cosmos DB Emulator

### ISSUE THREAD

**Issue by tumultuous1** [MicrosoftLearning/dp-420-cosmos-db-dev#41]
Code is not rendering properly at the end of the lab

    > &#128221; It may take a minute for all instances of the emulator to exit.

![image](https://user-images.githubusercontent.com/103527215/228040247-7719c43e-3ab7-420a-b3c3-232a7e59ef4d.png)

**Comment by MScalopez** [comment]
issue fixed
