### ISSUE TITLE
LAB Error: Process Azure Cosmos DB for NoSQL data using Azure Functions

### ISSUE THREAD

**Issue by chris-utter** [MicrosoftLearning/dp-420-cosmos-db-dev#42]
# Module: 
#### Step: 10

Description of issue
In the Data+Test section of the Function App, the log window is stuck "Connecting to Application Insights"

**Comment by MScalopez** [comment]
Thank you bringing this to our attention, @chris-utter, I will review this issue.

**Comment by MScalopez** [comment]
This issues was fixed on [issue 51](https://github.com/MicrosoftLearning/dp-420-cosmos-db-dev/issues/51).
