### ISSUE TITLE
Typos in instructions for lab 15

### ISSUE THREAD

**Issue by richardrigutins** [MicrosoftLearning/dp-420-cosmos-db-dev#46]
# Module: 07
#### Step: 00

Description of issue

There are some small typos in the instructions for lab 15 (instructions/15-cognitive-search.md).
For example:

- Line 154: `... can pick right back up form the same ...` should be `... can pick right back up from the same ...`.
- Line 213: `... giving a higher score to results that contains both terms ...` should be `... giving a higher score to results that contain both terms ...`.

Repro steps:

1. Open the instructions for lab 15 (instructions/15-cognitive-search.md).

**Comment by MScalopez** [comment]
@richardrigutins thank you for bringing this to our attention, fixed the typos.
