### ISSUE TITLE
Lab28 – Secrets placed differently and not viewable for student account

### ISSUE THREAD

**Issue by pstueck** [MicrosoftLearning/dp-420-cosmos-db-dev#48]
# Module: Implement security in Azure Cosmos DB for NoSQL 
#### Step: 4

The **Secrets** are no longer in the _Settings_ section but moved to _Objects_

#### Step: 6

Student accounts are not eligible to see secrets (but still can create them somehow) → cannot get the required **Secret Identifier** for oncoming steps.

#### Step: 4

No can do as I cannot get the **Secret Identifier**.

#### Step: 13

The deployment cannot commence because “This region has quota of 0 instances for your subscription. Try selecting different region or SKU.” But without knowing, which region does have quotas (for student accounts), this is a game of guessing (my first try was “West US” though).

#### Step: all

Lab time most likely too short to complete the whole lab.

**Comment by MScalopez** [comment]
Reviewing issue

**Comment by MScalopez** [comment]
Solution for the lab found, waiting for labs to be updated in production.

**Comment by MScalopez** [comment]
Fix in place, lab now works as expected.
