### ISSUE TITLE
Lab 17 issue redux

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/dp-420-cosmos-db-dev#55]
So, in #25 it was reported that unless you delete the Lab16 resource group, the deployment fails. 

I understand they are meant to be standalone labs, however, as we all have to use subscriptions provided by an ALH (given Azure Passes are no more), the ALHs group these two Module 8 labs together. 

To back up what @ejneuman said, can we not have an instruction stating resources need to be cleaned up after / prior lab 16/17 ? Or can ALHs be notified that they need to seperate the lab instances from one another?

**Comment by MScalopez** [comment]
@WigF1, @ejneuman, while our labs are meant to be run separately, I can see why it would be convenient to first check if the resources have been deployed and not try to re-deploy them.  I will go ahead and review the deployment scripts and include some code to check for this.  I will update this thread when that is done.  Thank you for your recommendations.

**Comment by MScalopez** [comment]
@WigF1, I followed your suggestion and added comments at the end of labs 16 and 17 to remove the resources created by the lab.  Additionally I added another comment right before the resource creation script to not run it if the resources already exist.
