### ISSUE TITLE
"Experiencing authentication issues" (various labs - when accessing Data Explorer in particular)

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/dp-420-cosmos-db-dev#56]
# Module: 00
#### Step: 01

Description of issue

I'll use Lab 1 as an example, but this seems to occur in various labs after one has successfully created the Azure Cosmos DB, and is then directed to click the 'Data Explorer'.  An error like so is popped:

![image](https://github.com/MicrosoftLearning/dp-420-cosmos-db-dev/assets/49700217/30a67920-e85a-4c3f-b521-866eaa8bfbd2)

Repro steps:

1. Take the course as written, create Azure Cosmos DB for NoSQL account, access Data Explorer. 
1. Regardless of error, it seems to be more of a warning then a blocker....one can apparently nevertheless ignore it and continue the steps to the end successfully.

Troubleshooting:

I have not seen this error before, in this course, or in others - but it *appears* as if there is something within Data Explorer that would very much like to connect to the Office Admin center and authenticate for some reason.  The Azure subscriptions we use would not normally ever have that allowed except insofar as a series might need to utilize Office admin...and if that was the case, a Student would receive an O365 Tenant, and not an Azure sub.

-I tested in a lab both with and without the ACPs used for security, and the behavior is the same even with no ACP restrictions - does not appear related to ACP blocking.

-I tested with several other subscriptions, both Prod and Dev, and received exactly the same error/warning, so it does not appear related to 'misconfiguration' of our normal sub used in this course.  (and this course/same sub/same config did not experience this error until some point recently)

Has anyone else seen this behavior, and perhaps can confirm it is an Azure-specific issue?

**Comment by MScalopez** [comment]
@TesterTesterson1004, sorry for the late response, this is now happening because we have limited the Azure Accounts used by the labs.  The labs used to use a supplied Azure subscription, but now have changed to Bring your Own Subscription.  If you use your own subscription you should no longer see these errors.
