### ISSUE TITLE
Creating new Container Issues - DP-420-Cosmos-DB-Dev

### ISSUE THREAD

**Issue by SkillableKA** [MicrosoftLearning/dp-420-cosmos-db-dev#57]
Description of issue:

If a lab is running multiple sets of instructions concurrently (i.e. 06-sdk-crud.md, 07-sdk-batch.md, 08-sdk-bulk.md) the user will run into an issue if the Azure Cosmos DB and container have already been created in an earlier set of instructions. It will give them an error about the resource already existing as the lab instance is still running, and the instructions do not note deleting the resources if doing multiple exercises one after the next. 

We've let the class know they'll need to delete the resource before creating another, but could an addition be added to the steps letting the user know they'll need to delete the Cosmos DB before attempting to create another in the following steps?

![image](https://github.com/MicrosoftLearning/dp-420-cosmos-db-dev/assets/169093291/42b537c4-6927-48df-a69f-0dca95af5770)

**Comment by MScalopez** [comment]
@SkillableKA, this is by design since every lab is meant to be run separately.  Note that we are doing a refresh in the next couple of month and will make sure to add you suggestion about deleting the resources at the end of each lab.
