### ISSUE TITLE
All labs from DP-420 is out of service

### ISSUE THREAD

**Issue by felipementel** [MicrosoftLearning/dp-420-cosmos-db-dev#59]
Here is feedback on how to make your question more effective

The provided question lacks necessary details and context for the community to be able to provide a prompt answer or solution. The title lacks key components such as Service, Scenario, and Result that can help the experts to filter and identify the problem effectively. The user should provide more information such as the technologies involved, the error messages, when they started seeing the issue, any troubleshooting efforts, and supporting materials. Without this information, it will be difficult for the community to determine next steps or provide a resolution.

Here are some improvements that can be made to the question to make it more effective:

Title:

"DP-420 Azure Exam Labs unresponsive: We're sorry. The lab environment needed to complete the exercises in this unit is temporarily unavailable."

Question:

Service: Azure, DP-420 Exam Labs (https://learn.microsoft.com/en-us/training/modules/perform-cross-document-transactional-operations-azure-cosmos-db-sql-api/4-exercise-batch-multiple-point-operations-together-sdk)

Scenario: I am unable to access DP-420 Exam Labs in Azure. Instead, I see an error message 'We're sorry. The lab environment needed to complete the exercises in this unit is temporarily unavailable.' on the screen. I have used this service in the past without any issues.

Result: My goal is to be able to access the Exam Labs and complete the course successfully.

Environment: I am using Windows 11 and the latest version of Microsoft Edge.

Troubleshooting efforts: I have tried clearing cache and cookies, restarting my computer and clearing DNS cache. These steps have not resolved the issue.

Supporting materials: Screenshot of the error message is attached.

With a more detailed question like this, the community can provide better assistance and resolve the issue.

Description of issue

![image](https://github.com/MicrosoftLearning/dp-420-cosmos-db-dev/assets/14238257/e8ff2be4-d39b-4f25-81a0-abc408dc2d6f)

Link: https://learn.microsoft.com/pt-br/training/modules/design-data-partitioning-strategy/7-exercise-advanced-modeling-patterns

**Comment by felipementel** [comment]
is this

**Comment by MScalopez** [comment]
@felipementel, thank you for bringing this to our attention. We are moving all these labs to Bring your own subscription by the end of the month.  I will work on updating the instructions to make sure you go directly to the GitHub repo instead of getting this error.

**Comment by felipementel** [comment]
Hi @MScalopez why did you close this issue? I´m interesting about this problem/solution

The problem still exists 
![image](https://github.com/user-attachments/assets/7efc43d9-d03f-4d11-a30d-f7df3a5abe32)

**Comment by MScalopez** [comment]
Sorry for the very long wait on this one.  For security reasons and to prevent misuse of our Virtual Machines, we have converted all our labs to Bring Your own Subscription.  You can now setup your environment and do the labs locally using your own Azure subscription or take advantage of using the free Azure trial to complete these labs.

**Comment by felipementel** [comment]
> Sorry for the very long wait on this one. For security reasons and to prevent misuse of our Virtual Machines, we have converted all our labs to Bring Your own Subscription. You can now setup your environment and do the labs locally using your own Azure subscription or take advantage of using the free Azure trial to complete these labs.

thank you for the reply
