### ISSUE TITLE
Create a provisioned account same database name twice 

### ISSUE THREAD

**Issue by Usamawahabkhan** [MicrosoftLearning/dp-420-cosmos-db-dev#8]
# Module: 02
#### Step: 00
Create a provisioned account

Description of issue

Repro steps:
<html>
<body>
<ol style="box-sizing: border-box; margin-top: 1rem; margin-bottom: 1rem; color: rgb(34, 34, 34); font-family: segoe-ui_normal, &quot;Segoe UI&quot;, Segoe, &quot;Segoe WP&quot;, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box;"><p style="box-sizing: border-box; margin-top: 1rem; margin-bottom: 0px;">Back in the<span> </span><strong style="box-sizing: border-box; font-weight: bolder;">Data Explorer</strong><span> </span>pane, expand the<span> </span><strong style="box-sizing: border-box; font-weight: bolder;">nothroughputdb</strong><span> </span>database node and then observe the<span> </span><strong style="box-sizing: border-box; font-weight: bolder;">requiredthroughputcontainer</strong><span> </span>container node within the hierarchy.</p></li><li style="box-sizing: border-box;"><p style="box-sizing: border-box; margin-top: 1rem; margin-bottom: 0px;">In the<span> </span><strong style="box-sizing: border-box; font-weight: bolder;">Data Explorer</strong><span> </span>pane, expand<span> </span><strong style="box-sizing: border-box; font-weight: bolder;">New Container</strong><span> </span>and then select<span> </span><strong style="box-sizing: border-box; font-weight: bolder;">New Database</strong>.</p></li><li style="box-sizing: border-box;"><p style="box-sizing: border-box; margin-top: 1rem; margin-bottom: 0px;">In the<span> </span><strong style="box-sizing: border-box; font-weight: bolder;">New Database</strong><span> </span>popup, enter the following values for each setting, and then select<span> </span><strong style="box-sizing: border-box; font-weight: bolder;">OK</strong>:</p>

Setting | Value
-- | --
Database id | manualthroughputdb
Share throughput across containers | Select this option
Database throughput | Manual
RU/s | 400

</li><li style="box-sizing: border-box;"><p style="box-sizing: border-box; margin-top: 1rem; margin-bottom: 0px;">Back in the<span> </span><strong style="box-sizing: border-box; font-weight: bolder;">Data Explorer</strong><span> </span>pane, expand the<span> </span><strong style="box-sizing: border-box; font-weight: bolder;">manualthroughputdb</strong><span> </span>database node and then observe the<span> </span><strong style="box-sizing: border-box; font-weight: bolder;">childcontainer</strong><span> </span>container node within the hierarchy.</p></li></ol>
</body>
</html>

In the New Database popup, enter the following values for each setting, and then select OK:

we have created database manualthroughputdb on step number 16 then again we have to create db with same name on step 19
manualthroughputdb can not be created again

**Comment by MScalopez** [comment]
@Usamawahabkhan, thank you for bringing this to our attention, label has been corrected to "Use existing"
