### ISSUE TITLE
Missing file in 17-denormalize lab folder

### ISSUE THREAD

**Issue by dabrock51** [MicrosoftLearning/dp-420-cosmos-db-dev#9]
# Module: 08
#### Step: 03

Description of issue
When attempting to execute one of the program's options an error occurs:
The type initializer for 'Progfam' threw an exception ... The configuration file 'appSettings.json' was not found and is not optional.
The file is not in the folder.
![17-denornalize-error](https://user-images.githubusercontent.com/32367563/157363174-6f4b8b0a-a05d-452b-af7c-34e85f0fb3a7.png)

Screenshot is attached.

**Comment by MScalopez** [comment]
@dabrock51, thank you for bringing this up to our attention, I will review this issue and fix it as necessary.

**Comment by MScalopez** [comment]
Issue has been fixed
